"""Firewall, audit, accounts, and DNS registry tweaks."""

ADVANCED_TWEAKS = [
    # ── Firewall ──
    {
        "id": "firewall_enable_all",
        "name": "Enable Firewall (All Profiles)",
        "category": "firewall",
        "info": "Ensures Windows Firewall is enabled on Domain, Private, and Public network profiles.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile",
        "value": "EnableFirewall",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_block_inbound_domain",
        "name": "Block Inbound (Domain Profile)",
        "category": "firewall",
        "info": "Default inbound action = Block on domain networks. Only explicit allow rules pass.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile",
        "value": "DefaultInboundAction",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_block_inbound_private",
        "name": "Block Inbound (Private Profile)",
        "category": "firewall",
        "info": "Default inbound action = Block on private/home networks.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile",
        "value": "DefaultInboundAction",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_block_inbound_public",
        "name": "Block Inbound (Public Profile)",
        "category": "firewall",
        "info": "Default inbound action = Block on public networks. Critical for laptops on untrusted Wi-Fi.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile",
        "value": "DefaultInboundAction",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_disable_notifications",
        "name": "Disable Firewall Notifications",
        "category": "firewall",
        "info": "Suppresses firewall popup notifications that can leak network context to shoulder surfers.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile",
        "value": "DisableNotifications",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_log_dropped",
        "name": "Log Dropped Packets",
        "category": "firewall",
        "info": "Logs blocked inbound/outbound connections to pfirewall.log for forensic review.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging",
        "value": "LogDroppedPackets",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_log_success",
        "name": "Log Successful Connections",
        "category": "firewall",
        "info": "Logs allowed connections — useful for incident response and baseline analysis.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging",
        "value": "LogSuccessfulConnections",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "firewall_no_auth_fallback",
        "name": "Block Unauthenticated Fallback",
        "category": "firewall",
        "info": "Prevents fallback to less secure auth methods when IPsec auth fails.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy",
        "value": "DoNotAllowUnauthenticatedRPC",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    # ── Audit ──
    {
        "id": "audit_base_objects",
        "name": "Audit Base Objects",
        "category": "audit",
        "info": "Audits access to securable objects (files, registry keys). Essential for forensic trails.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "AuditBaseObjects",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "audit_base_directories",
        "name": "Audit Base Directories",
        "category": "audit",
        "info": "Audits container object access. Logs when folders/containers are accessed.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "AuditBaseDirectories",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "audit_process_creation",
        "name": "Audit Process Creation",
        "category": "audit",
        "info": "Logs every new process with command line (Event ID 4688). Key for detecting malware execution.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit",
        "value": "ProcessCreationIncludeCmdLine_Enabled",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "audit_logon_events",
        "name": "Audit Logon Events",
        "category": "audit",
        "info": "Advanced audit policy for logon/logoff events. Tracks authentication attempts.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "SCENoApplyLegacyAuditPolicy",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "audit_credential_validation",
        "name": "Audit Credential Validation",
        "category": "audit",
        "info": "Logs success/failure of credential validation (Event ID 4776). Detects brute force.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\Netlogon\Parameters",
        "value": "AuditCredentialValidation",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "audit_privilege_use",
        "name": "Audit Privilege Use",
        "category": "audit",
        "info": "Logs when sensitive privileges (SeDebug, SeBackup) are exercised.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "FullPrivilegeAuditing",
        "value_type": "dword",
        "on": 3,
        "off": 0,
    },
    {
        "id": "audit_security_event_log_size",
        "name": "Increase Security Log Size",
        "category": "audit",
        "info": "Sets Security event log max size to 256MB so audit data isn't overwritten quickly.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\EventLog\Security",
        "value": "MaxSize",
        "value_type": "dword",
        "on": 268435456,
        "off": 20971520,
    },
    {
        "id": "audit_retention_security",
        "name": "Retain Security Logs",
        "category": "audit",
        "info": "Security log retention = do not overwrite events automatically. Preserve for investigations.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\EventLog\Security",
        "value": "Retention",
        "value_type": "sz",
        "on": "0",
        "off": "",
    },
    # ── Accounts ──
    {
        "id": "account_lockout_threshold",
        "name": "Account Lockout Threshold (5)",
        "category": "accounts",
        "info": "Locks account after 5 failed logon attempts. Slows brute-force password attacks.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "MaxBadPasswordsAllowed",
        "value_type": "dword",
        "on": 5,
        "off": 0,
    },
    {
        "id": "account_lockout_duration",
        "name": "Account Lockout Duration (30 min)",
        "category": "accounts",
        "info": "Locked accounts stay locked for 30 minutes before retry is allowed.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "LockoutBadCount",
        "value_type": "dword",
        "on": 30,
        "off": 0,
    },
    {
        "id": "account_min_password_length",
        "name": "Minimum Password Length (14)",
        "category": "accounts",
        "info": "Requires passwords of at least 14 characters. Aligns with NIST/CIS recommendations.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\SAM",
        "value": "MinimumPasswordLength",
        "value_type": "dword",
        "on": 14,
        "off": 0,
    },
    {
        "id": "account_password_complexity",
        "name": "Require Password Complexity",
        "category": "accounts",
        "info": "Enforces uppercase, lowercase, numbers, and symbols in passwords.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "LimitBlankPasswordUse",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "account_disable_guest",
        "name": "Disable Guest Account (Policy)",
        "category": "accounts",
        "info": "Policy-level guest account disable. Prevents anonymous local access.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "EnableGuestAccount",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "account_no_last_username",
        "name": "Hide Last Signed-In User",
        "category": "accounts",
        "info": "Login screen won't show the last username. Reduces account enumeration at logon.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "DontDisplayLastUserName",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "account_inactivity_limit",
        "name": "Machine Inactivity Limit",
        "category": "accounts",
        "info": "Forces logoff/sleep after 900 seconds of inactivity on the lock screen.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "InactivityTimeoutSecs",
        "value_type": "dword",
        "on": 900,
        "off": 0,
    },
    {
        "id": "account_disable_credential_manager",
        "name": "Disable Credential Manager",
        "category": "accounts",
        "info": "Stops Windows Credential Manager from storing web and network passwords locally.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation",
        "value": "AllowProtectedCreds",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    # ── DNS ──
    {
        "id": "dns_enable_doh",
        "name": "Enable DNS over HTTPS",
        "category": "dns",
        "info": "Forces DNS queries over HTTPS. Prevents ISP/local network DNS snooping and injection.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
        "value": "EnableAutoDoh",
        "value_type": "dword",
        "on": 2,
        "off": 0,
    },
    {
        "id": "dns_disable_smart_multi_homed",
        "name": "Disable Smart Multi-Homed DNS",
        "category": "dns",
        "info": "Stops Windows from sending DNS queries to all adapters simultaneously. Reduces DNS leaks.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\Dnscache\Parameters",
        "value": "DisableParallelAandAAAA",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "dns_disable_multicast",
        "name": "Disable Multicast DNS (Policy)",
        "category": "dns",
        "info": "Policy-level mDNS disable. Complements LLMNR hardening for local name resolution.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
        "value": "EnableMulticast",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "dns_disable_negative_cache",
        "name": "Disable Negative DNS Cache",
        "category": "dns",
        "info": "Don't cache failed DNS lookups. Useful when switching VPN/DNS to avoid stale NXDOMAIN.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
        "value": "DisableNegativeCache",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "dns_secure_name_query",
        "name": "Require Secure Name Query",
        "category": "dns",
        "info": "Requires DNSSEC validation where supported. Rejects unsigned DNS responses.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\DNSCache\Parameters",
        "value": "EnableDnsSec",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "dns_disable_adapter_domain_name",
        "name": "Disable Adapter Domain Name Registration",
        "category": "dns",
        "info": "Stops this PC from registering its hostname on the DNS domain automatically.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters",
        "value": "DisableDynamicUpdate",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
]
