"""Recommended apps — privacy, security, dev tools."""

DOWNLOADS = [
    {
        "id": "telegram",
        "name": "Telegram",
        "desc": "Cloud-based messaging with optional secret chats",
        "category": "Communication",
        "url": "https://desktop.telegram.org/",
    },
    {
        "id": "signal",
        "name": "Signal",
        "desc": "End-to-end encrypted messaging and calls",
        "category": "Communication",
        "url": "https://signal.org/download/windows/",
    },
    {
        "id": "proton_mail",
        "name": "Proton Mail",
        "desc": "Encrypted email — desktop app and Bridge",
        "category": "Communication",
        "url": "https://proton.me/mail/download",
    },
    {
        "id": "element",
        "name": "Element",
        "desc": "Matrix protocol client for decentralized chat",
        "category": "Communication",
        "url": "https://element.io/download",
    },
    {
        "id": "session",
        "name": "Session",
        "desc": "Anonymous encrypted messenger — no phone number",
        "category": "Communication",
        "url": "https://getsession.org/download",
    },
    {
        "id": "mullvad_vpn",
        "name": "Mullvad VPN",
        "desc": "Privacy-focused VPN — no email required to sign up",
        "category": "VPN & Privacy",
        "url": "https://mullvad.net/en/download/windows",
    },
    {
        "id": "proton_vpn",
        "name": "Proton VPN",
        "desc": "Swiss-based VPN from the Proton team",
        "category": "VPN & Privacy",
        "url": "https://protonvpn.com/download-windows",
    },
    {
        "id": "tor_browser",
        "name": "Tor Browser",
        "desc": "Browse over the Tor anonymity network",
        "category": "VPN & Privacy",
        "url": "https://www.torproject.org/download/",
    },
    {
        "id": "vscode",
        "name": "Visual Studio Code",
        "desc": "Lightweight code editor with huge extension ecosystem",
        "category": "Development",
        "url": "https://code.visualstudio.com/download",
    },
    {
        "id": "virtualbox",
        "name": "VirtualBox",
        "desc": "Free VM hypervisor for isolated environments",
        "category": "Development",
        "url": "https://www.virtualbox.org/wiki/Downloads",
    },
    {
        "id": "winscp",
        "name": "WinSCP",
        "desc": "SFTP/SCP/FTP client for secure file transfer",
        "category": "Development",
        "url": "https://winscp.net/eng/download.php",
    },
    {
        "id": "git",
        "name": "Git for Windows",
        "desc": "Version control with bash shell included",
        "category": "Development",
        "url": "https://git-scm.com/download/win",
    },
    {
        "id": "putty",
        "name": "PuTTY",
        "desc": "SSH and telnet client for remote shells",
        "category": "Development",
        "url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html",
    },
    {
        "id": "wireshark",
        "name": "Wireshark",
        "desc": "Network packet analyzer for traffic inspection",
        "category": "Development",
        "url": "https://www.wireshark.org/download.html",
    },
    {
        "id": "keepassxc",
        "name": "KeePassXC",
        "desc": "Offline password manager with local encrypted vault",
        "category": "Security",
        "url": "https://keepassxc.org/download/",
    },
    {
        "id": "bitwarden",
        "name": "Bitwarden",
        "desc": "Open-source password manager — self-hostable",
        "category": "Security",
        "url": "https://bitwarden.com/download/",
    },
    {
        "id": "veracrypt",
        "name": "VeraCrypt",
        "desc": "Full-disk and container encryption — TrueCrypt successor",
        "category": "Security",
        "url": "https://www.veracrypt.fr/en/Downloads.html",
    },
    {
        "id": "exif_cleaner",
        "name": "ExifCleaner",
        "desc": "Strip metadata (GPS, camera info) from images before sharing",
        "category": "Security",
        "url": "https://github.com/szTheory/exif-cleaner/releases",
    },
    {
        "id": "bleachbit",
        "name": "BleachBit",
        "desc": "Clean temp files, caches, and shred sensitive data",
        "category": "Security",
        "url": "https://www.bleachbit.org/download/windows",
    },
    {
        "id": "firefox",
        "name": "Firefox",
        "desc": "Open-source browser with strong privacy controls",
        "category": "Browsers",
        "url": "https://www.mozilla.org/firefox/download/",
    },
    {
        "id": "librewolf",
        "name": "LibreWolf",
        "desc": "Firefox fork with privacy hardening out of the box",
        "category": "Browsers",
        "url": "https://librewolf.net/installation/windows/",
    },
    {
        "id": "spotify",
        "name": "Spotify",
        "desc": "Music streaming — use a burner account for privacy",
        "category": "Media",
        "url": "https://www.spotify.com/download/windows/",
    },
    {
        "id": "vlc",
        "name": "VLC Media Player",
        "desc": "Plays everything locally — no account, no cloud",
        "category": "Media",
        "url": "https://www.videolan.org/vlc/download-windows.html",
    },
    {
        "id": "7zip",
        "name": "7-Zip",
        "desc": "Archive tool with AES-256 encryption support",
        "category": "Utilities",
        "url": "https://www.7-zip.org/download.html",
    },
    {
        "id": "notepadpp",
        "name": "Notepad++",
        "desc": "Fast text editor for logs, configs, and scripts",
        "category": "Utilities",
        "url": "https://notepad-plus-plus.org/downloads/",
    },
    {
        "id": "everything",
        "name": "Everything Search",
        "desc": "Instant local file search — nothing leaves your machine",
        "category": "Utilities",
        "url": "https://www.voidtools.com/downloads/",
    },
    {
        "id": "proton_drive",
        "name": "Proton Drive",
        "desc": "End-to-end encrypted cloud storage",
        "category": "VPN & Privacy",
        "url": "https://proton.me/drive/download",
    },
    {
        "id": "simplelogin",
        "name": "SimpleLogin",
        "desc": "Email aliasing to hide your real address",
        "category": "VPN & Privacy",
        "url": "https://simplelogin.io/download/",
    },
]

DOWNLOAD_BY_ID = {d["id"]: d for d in DOWNLOADS}
