"""One-click hardening profiles for field deployment."""

PROFILES = [
    {
        "id": "baseline",
        "name": "Baseline",
        "info": "Minimum recommended hardening for any Windows endpoint. Safe for most environments.",
        "level": "low",
        "registry": [
            "allow_telemetry_zero",
            "no_lm_hash",
            "restrict_anonymous",
            "enable_lua",
            "disable_advertising_id",
            "show_file_extensions",
            "firewall_enable_all",
            "firewall_block_inbound_public",
        ],
        "services": ["diagtrack", "dmwappushservice"],
    },
    {
        "id": "operational_security",
        "name": "Operational Security",
        "info": "Standard OPSEC profile — telemetry off, network hardened, key services disabled.",
        "level": "medium",
        "registry": [
            "allow_telemetry_zero",
            "no_lm_hash",
            "restrict_anonymous",
            "restrict_anonymous_sam",
            "wdigest_no_credential",
            "run_as_ppl",
            "disable_ntlm_fallback",
            "disable_llmnr",
            "disable_wpad",
            "disable_smb1",
            "disable_rdp",
            "disable_remote_assistance",
            "disable_advertising_id",
            "disable_location_tracking",
            "disable_cortana",
            "show_file_extensions",
            "show_hidden_files",
            "firewall_enable_all",
            "firewall_block_inbound_private",
            "firewall_block_inbound_public",
            "dns_enable_doh",
            "audit_process_creation",
        ],
        "services": [
            "diagtrack",
            "dmwappushservice",
            "remote_registry",
            "wersvc",
            "lfsvc",
            "cdpsvc",
            "dosvc",
            "ssdpsrv",
            "upnphost",
            "winhttp_autoproxy",
        ],
    },
    {
        "id": "maximum_opsec",
        "name": "Maximum OPSEC",
        "info": "Aggressive hardening for high-risk environments. May break some apps, RDP, USB, printing.",
        "level": "high",
        "registry": [
            "allow_telemetry_zero",
            "no_lm_hash",
            "restrict_anonymous",
            "restrict_anonymous_sam",
            "wdigest_no_credential",
            "run_as_ppl",
            "disable_ntlm_fallback",
            "restrict_receiving_ntlm",
            "ntlm_min_client_sec",
            "disable_llmnr",
            "disable_wpad",
            "disable_smb1",
            "smb_require_signing",
            "disable_rdp",
            "disable_usb_storage",
            "disable_script_host",
            "disable_remote_assistance",
            "disable_print_spooler",
            "clear_pagefile_shutdown",
            "local_account_token_filter",
            "disable_autoplay",
            "disable_autorun",
            "smartscreen_require_admin",
            "firewall_enable_all",
            "firewall_block_inbound_domain",
            "firewall_block_inbound_private",
            "firewall_block_inbound_public",
            "firewall_log_dropped",
            "audit_base_objects",
            "audit_process_creation",
            "audit_credential_validation",
            "account_no_last_username",
            "dns_enable_doh",
            "dns_disable_smart_multi_homed",
        ],
        "services": [
            "diagtrack",
            "dmwappushservice",
            "remote_registry",
            "wersvc",
            "lfsvc",
            "cdpsvc",
            "dosvc",
            "ssdpsrv",
            "upnphost",
            "winhttp_autoproxy",
            "termservice",
            "xblauthmanager",
            "xblgamesave",
            "xboxgipsvc",
            "xboxnetapisvc",
            "pnrpsvc",
            "icssvc",
            "edgeupdate",
            "edgeupdatem",
        ],
    },
    {
        "id": "privacy_focused",
        "name": "Privacy Focused",
        "info": "Strips telemetry and tracking without aggressive network lockdown. Good for daily drivers.",
        "level": "medium",
        "registry": [
            "allow_telemetry_zero",
            "disable_windows_consumer_features",
            "disable_tailored_experiences",
            "disable_cloud_optimized_content",
            "disable_advertising_id",
            "disable_location_tracking",
            "disable_cortana",
            "disable_web_search",
            "disable_cloud_clipboard",
            "disable_activity_history",
            "disable_app_access_microphone",
            "disable_app_access_camera",
            "disable_wifi_sense",
            "disable_error_reporting",
            "disable_edge_signin",
        ],
        "services": ["diagtrack", "dmwappushservice", "cdpsvc", "lfsvc"],
    },
    {
        "id": "audit_compliance",
        "name": "Audit & Compliance",
        "info": "Enables comprehensive logging and audit policies for forensic readiness and compliance.",
        "level": "medium",
        "registry": [
            "audit_base_objects",
            "audit_base_directories",
            "audit_process_creation",
            "audit_logon_events",
            "audit_credential_validation",
            "audit_privilege_use",
            "audit_security_event_log_size",
            "audit_retention_security",
            "firewall_log_dropped",
            "firewall_log_success",
            "account_lockout_threshold",
            "account_no_last_username",
        ],
        "services": ["diagtrack"],
    },
]

PROFILE_BY_ID = {p["id"]: p for p in PROFILES}
