"""Registry tweak definitions for Windows hardening / OPSEC."""

# Each tweak: id, name, info, hive (HKLM/HKCU), path, value, value_type (dword/sz),
# on = hardened state, off = revert/default state

REGISTRY_TWEAKS = [
    # ── User-requested ──
    {
        "id": "smartscreen_require_admin",
        "name": "SmartScreen Require Admin",
        "info": "Sets SmartScreenEnabled to RequireAdmin. Downloads and apps need admin approval before running — reduces drive-by malware installs.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer",
        "value": "SmartScreenEnabled",
        "value_type": "sz",
        "on": "RequireAdmin",
        "off": "Warn",
    },
    {
        "id": "no_lm_hash",
        "name": "No LM Hash",
        "info": "Stores passwords using NTLM only, not the weak LM hash. Stops LM hashes from being saved on this machine.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "NoLMHash",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "restrict_anonymous",
        "name": "Restrict Anonymous",
        "info": "Blocks anonymous users from connecting to pipes and shares. Closes a common recon/exploit path on the network.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "RestrictAnonymous",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "wdigest_no_credential",
        "name": "Disable WDigest Credential Caching",
        "info": "Stops plaintext credentials from being stored in memory via WDigest. Important hardening — Mimikatz targets this.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest",
        "value": "UseLogonCredential",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_windows_consumer_features",
        "name": "Disable Consumer Features",
        "info": "Stops Windows from silently installing suggested apps and consumer bloat from the Store.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "value": "DisableWindowsConsumerFeatures",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "allow_telemetry_zero",
        "name": "Disable Telemetry",
        "info": "Sets AllowTelemetry to 0. Cuts most diagnostic and usage data sent to Microsoft.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "value": "AllowTelemetry",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    # ── LSA / Authentication ──
    {
        "id": "restrict_anonymous_sam",
        "name": "Restrict Anonymous SAM",
        "info": "Prevents anonymous users from enumerating SAM accounts. Stops null-session user listing.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "RestrictAnonymousSAM",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "lm_compatibility_level",
        "name": "NTLMv2 Only",
        "info": "Sets LmCompatibilityLevel to 5 — only NTLMv2 responses, no LM or NTLMv1. Better auth security on the wire.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "LmCompatibilityLevel",
        "value_type": "dword",
        "on": 5,
        "off": 3,
    },
    {
        "id": "limit_blank_password_use",
        "name": "Limit Blank Password Use",
        "info": "Blocks remote logons for accounts with blank passwords. Only local console can use blank passwords.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "LimitBlankPasswordUse",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "everyone_includes_anonymous",
        "name": "Everyone Excludes Anonymous",
        "info": "Anonymous tokens no longer included in the Everyone group. Tightens access for null sessions.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "EveryoneIncludesAnonymous",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_domain_creds",
        "name": "Disable Domain Cred Caching",
        "info": "WDigest won't cache domain credentials in memory. Extra layer against credential theft.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest",
        "value": "DisableDomainCreds",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "local_account_token_filter",
        "name": "Restrict Remote Local Admin",
        "info": "LocalAccountTokenFilterPolicy = 1. Remote connections can't use full admin token on local accounts (Pass-the-Hash mitigation).",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "LocalAccountTokenFilterPolicy",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "enable_lua",
        "name": "UAC Enabled",
        "info": "Keeps User Account Control on. Disabling UAC is one of the worst things you can do for security.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "EnableLUA",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_auto_restart_signon",
        "name": "Disable Auto-Restart Sign-On",
        "info": "After Windows Update reboot, won't auto-log you back in. Stops unattended unlocked sessions.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "DisableAutomaticRestartSignOn",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    # ── Network / SMB ──
    {
        "id": "disable_smb1",
        "name": "Disable SMBv1",
        "info": "Turns off SMB 1.0 — vulnerable to EternalBlue-style attacks. You almost never need it.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
        "value": "SMB1",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "smb_require_signing",
        "name": "Require SMB Signing",
        "info": "Forces SMB packet signing on the server. Prevents tampering and relay attacks on the network.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
        "value": "RequireSecuritySignature",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "smb_enable_signing",
        "name": "Enable SMB Signing",
        "info": "Enables SMB signing on outgoing server connections. Works with require signing for full protection.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
        "value": "EnableSecuritySignature",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_icmp_redirect",
        "name": "Disable ICMP Redirects",
        "info": "Windows won't accept ICMP redirect packets. Stops MITM route manipulation on local networks.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters",
        "value": "EnableICMPRedirect",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "block_non_domain_network",
        "name": "Block Non-Domain Networks",
        "info": "When on a domain, blocks connection to non-domain networks when a domain network is available.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\Network Connections",
        "value": "NC_AllowNetBridge_NLA",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    # ── Privacy / Telemetry (HKLM policies) ──
    {
        "id": "disable_feedback_notifications",
        "name": "Disable Feedback Notifications",
        "info": "Stops Windows from nagging you to send feedback to Microsoft.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "value": "DoNotShowFeedbackNotifications",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_tailored_experiences",
        "name": "Disable Tailored Experiences",
        "info": "Diagnostic data won't be used to personalize ads, tips, and recommendations.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "value": "DisableTailoredExperiencesWithDiagnosticData",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_cloud_optimized_content",
        "name": "Disable Cloud Optimized Content",
        "info": "Blocks cloud-delivered content like suggestions in Settings and Start.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "value": "DisableCloudOptimizedContent",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_consumer_account_state",
        "name": "Disable Consumer Account Content",
        "info": "Stops Windows from syncing consumer account state and promotional content.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "value": "DisableConsumerAccountStateContent",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_cdp",
        "name": "Disable Connected Devices Platform",
        "info": "Turns off cross-device sync features (Your Phone, cross-device clipboard via CDP).",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\System",
        "value": "EnableCdp",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    # ── Remote access ──
    {
        "id": "disable_remote_assistance",
        "name": "Disable Remote Assistance",
        "info": "Nobody can connect to your PC via Windows Remote Assistance. Good default for most users.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Remote Assistance",
        "value": "fAllowToGetHelp",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_autoplay",
        "name": "Disable Autoplay",
        "info": "USB and removable drives won't auto-run content. Stops a classic malware delivery method.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "value": "NoDriveTypeAutoRun",
        "value_type": "dword",
        "on": 255,
        "off": 145,
    },
    {
        "id": "disable_autorun",
        "name": "Disable Autorun",
        "info": "Completely disables Autorun for all drive types. Stronger than autoplay alone.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "value": "NoAutorun",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    # ── Windows Defender / Security ──
    {
        "id": "disable_remote_registry_service",
        "name": "Disable Remote Registry (Policy)",
        "info": "Policy flag to disable the Remote Registry service from starting. Closes remote registry edits.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\RemoteRegistry",
        "value": "Start",
        "value_type": "dword",
        "on": 4,
        "off": 3,
    },
    {
        "id": "enable_smart_screen_edge",
        "name": "Edge SmartScreen Block",
        "info": "Microsoft Edge SmartScreen set to block (1) instead of warn. Applies to Edge downloads.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter",
        "value": "EnabledV9",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    # ── HKCU Privacy ──
    {
        "id": "disable_advertising_id",
        "name": "Disable Advertising ID",
        "info": "Turns off your Windows advertising ID. Apps can't use it for tracking or targeted ads.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo",
        "value": "Enabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_location_tracking",
        "name": "Disable Location Tracking",
        "info": "System-wide location access off for your user account. Maps and weather may break.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_cortana",
        "name": "Disable Cortana",
        "info": "Cortana and web search in Start are off. Local search still works.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search",
        "value": "CortanaEnabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_web_search",
        "name": "Disable Web Search in Start",
        "info": "Start menu search won't query Bing. Results stay local only.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search",
        "value": "BingSearchEnabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_cloud_clipboard",
        "name": "Disable Cloud Clipboard",
        "info": "Clipboard history stays on this PC. Won't sync to other devices.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Clipboard",
        "value": "EnableCloudClipboard",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_activity_history",
        "name": "Disable Activity History",
        "info": "Timeline and activity history won't upload to Microsoft. Other devices won't see your activity.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy",
        "value": "PublishUserActivities",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_tailored_experiences_hkcu",
        "name": "Disable Tailored Experiences (User)",
        "info": "Your diagnostic data won't personalize tips and ads for your account.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy",
        "value": "TailoredExperiencesWithDiagnosticDataEnabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_app_launch_tracking",
        "name": "Disable App Launch Tracking",
        "info": "Windows won't track which apps you launch to improve Start and search suggestions.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "value": "Start_TrackProgs",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_wifi_sense",
        "name": "Disable WiFi Sense",
        "info": "Stops automatic connection to open hotspots and sharing Wi-Fi profiles.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config",
        "value": "AutoConnectAllowedOEM",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_suggestions",
        "name": "Disable Settings Suggestions",
        "info": "Settings app won't show suggested content and tips from Microsoft.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "value": "SubscribedContent-338393Enabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_lock_screen_suggestions",
        "name": "Disable Lock Screen Tips",
        "info": "No tips, fun facts, or ads on the lock screen.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
        "value": "SubscribedContent-310093Enabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_error_reporting",
        "name": "Disable Error Reporting",
        "info": "Windows Error Reporting won't send crash dumps and data to Microsoft.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\Windows Error Reporting",
        "value": "Disabled",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_input_personalization",
        "name": "Disable Input Personalization",
        "info": "Speech and typing data won't be collected to improve language recognition.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Personalization\Settings",
        "value": "AcceptedPrivacyPolicy",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_app_access_microphone",
        "name": "Block App Microphone Access",
        "info": "Default policy denies microphone access for apps unless you allow per-app.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_app_access_camera",
        "name": "Block App Camera Access",
        "info": "Default policy denies camera access for apps unless you allow per-app.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    # ── Additional hardening ──
    {
        "id": "run_as_ppl",
        "name": "RunAsPPL (LSA Protection)",
        "info": "Runs LSA as a Protected Process Light. Makes credential dumping much harder. Requires a reboot to take effect.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
        "value": "RunAsPPL",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_ntlm_fallback",
        "name": "Disable NTLM Fallback",
        "info": "RestrictSendingNTLMTicket = 1. Stops this PC from sending NTLM auth to remote servers — blocks relay and pass-the-hash over the network.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0",
        "value": "RestrictSendingNTLMTicket",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_script_host",
        "name": "Disable Windows Script Host",
        "info": "Turns off WSH (.vbs / .js script execution). Stops a common malware delivery method. May break old logon scripts.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows Script Host\Settings",
        "value": "Enabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "show_file_extensions",
        "name": "Show File Extensions",
        "info": "Shows extensions like .exe and .pdf in Explorer. Makes it harder for malware to disguise files as documents.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "value": "HideFileExt",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "show_hidden_files",
        "name": "Show Hidden Files",
        "info": "Shows hidden files and folders in Explorer. Useful for spotting suspicious hidden files on the system.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
        "value": "Hidden",
        "value_type": "dword",
        "on": 1,
        "off": 2,
    },
    {
        "id": "disable_llmnr",
        "name": "Disable LLMNR",
        "info": "Turns off Link-Local Multicast Name Resolution. Stops local network poisoning attacks that intercept name lookups.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
        "value": "EnableMulticast",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_wpad",
        "name": "Disable WPAD Auto-Discovery",
        "info": "Stops Windows from auto-detecting proxy settings via WPAD. Closes a common MITM attack vector on local networks.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings",
        "value": "WpadOverride",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_usb_storage",
        "name": "Disable USB Storage",
        "info": "Blocks USB mass storage devices from mounting. Prevents data theft via flash drives. Other USB devices still work.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\USBSTOR",
        "value": "Start",
        "value_type": "dword",
        "on": 4,
        "off": 3,
    },
    {
        "id": "disable_rdp",
        "name": "Disable Remote Desktop",
        "info": "Turns off Remote Desktop connections to this PC. Only disable if you don't need to RDP into this machine.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server",
        "value": "fDenyTSConnections",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
]

from registry_extra import EXTRA_REGISTRY_TWEAKS
from advanced_tweaks import ADVANCED_TWEAKS

REGISTRY_TWEAKS.extend(EXTRA_REGISTRY_TWEAKS)
REGISTRY_TWEAKS.extend(ADVANCED_TWEAKS)

NETWORK_IDS = {
    "restrict_anonymous", "disable_smb1", "smb_require_signing", "smb_enable_signing",
    "disable_icmp_redirect", "block_non_domain_network", "disable_ntlm_fallback",
    "disable_llmnr", "disable_wpad", "disable_winhttp_autoproxy",
}

PRIVACY_IDS = {
    "disable_windows_consumer_features", "allow_telemetry_zero",
    "disable_feedback_notifications", "disable_tailored_experiences",
    "disable_cloud_optimized_content", "disable_consumer_account_state",
    "disable_cdp", "disable_advertising_id", "disable_location_tracking",
    "disable_cortana", "disable_web_search", "disable_cloud_clipboard",
    "disable_activity_history", "disable_tailored_experiences_hkcu",
    "disable_app_launch_tracking", "disable_wifi_sense", "disable_suggestions",
    "disable_lock_screen_suggestions", "disable_error_reporting",
    "disable_input_personalization", "disable_app_access_microphone",
    "disable_app_access_camera",
}

EXPLORER_IDS = {
    "smartscreen_require_admin", "disable_autoplay", "disable_autorun",
    "show_file_extensions", "show_hidden_files", "enable_smart_screen_edge",
}

for tweak in REGISTRY_TWEAKS:
    if "category" in tweak:
        continue
    tid = tweak["id"]
    if tid in NETWORK_IDS:
        tweak["category"] = "network"
    elif tid in PRIVACY_IDS:
        tweak["category"] = "privacy"
    elif tid in EXPLORER_IDS:
        tweak["category"] = "explorer"
    else:
        tweak["category"] = "security"

TWEAK_BY_ID = {t["id"]: t for t in REGISTRY_TWEAKS}
