"""Additional registry hardening tweaks — merged into registry_tweaks."""

EXTRA_REGISTRY_TWEAKS = [
    {
        "id": "restrict_receiving_ntlm",
        "name": "Restrict Incoming NTLM",
        "category": "network",
        "info": "RestrictReceivingNTLMTraffic = 1. Blocks incoming NTLM auth from remote machines — stops relay attacks targeting this PC.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0",
        "value": "RestrictReceivingNTLMTraffic",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "ntlm_min_client_sec",
        "name": "NTLM Minimum Client Security",
        "category": "network",
        "info": "Forces NTLMv2 + 128-bit encryption + signing on outbound NTLM. Drops weak legacy NTLM handshakes.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0",
        "value": "NTLMMinClientSec",
        "value_type": "dword",
        "on": 537395200,
        "off": 536870912,
    },
    {
        "id": "ntlm_min_server_sec",
        "name": "NTLM Minimum Server Security",
        "category": "network",
        "info": "Same minimum security bar for inbound NTLM on this machine. Pairs with client-side NTLM hardening.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0",
        "value": "NTLMMinServerSec",
        "value_type": "dword",
        "on": 537395200,
        "off": 536870912,
    },
    {
        "id": "disable_insecure_guest_auth",
        "name": "Disable Insecure Guest Logons",
        "category": "network",
        "info": "Blocks anonymous/insecure guest access to SMB shares. Stops credential-less share access exploits.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters",
        "value": "AllowInsecureGuestAuth",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "workstation_require_signing",
        "name": "Require SMB Client Signing",
        "category": "network",
        "info": "Outgoing SMB connections must use packet signing. Prevents tampering on file shares you connect to.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters",
        "value": "RequireSecuritySignature",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_netbios",
        "name": "Disable NetBIOS over TCP/IP",
        "category": "network",
        "info": "Turns off NetBIOS name resolution on all adapters. Cuts legacy name-service attacks on LANs.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\NetBT\Parameters",
        "value": "DisableNetbiosOption",
        "value_type": "dword",
        "on": 2,
        "off": 0,
    },
    {
        "id": "disable_delivery_optimization",
        "name": "Disable Delivery Optimization",
        "category": "network",
        "info": "Stops Windows Update from sharing downloaded updates with other PCs on your network or internet.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization",
        "value": "DODownloadMode",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_wins",
        "name": "Disable WINS Resolution",
        "category": "network",
        "info": "Disables legacy WINS name lookup. You won't need this unless you're on ancient corporate networks.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\NetBT\Parameters",
        "value": "DisableWINS",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "encryption_oracle_fix",
        "name": "Block Encryption Oracle (CredSSP)",
        "category": "network",
        "info": "AllowEncryptionOracle = 0. Blocks vulnerable CredSSP sessions exploited by CVE-2018-0886.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters",
        "value": "AllowEncryptionOracle",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_winhttp_autoproxy",
        "name": "Disable WinHTTP Auto-Proxy Service",
        "category": "network",
        "info": "Disables the WinHttpAutoProxy service via policy. Extra layer on top of WPAD registry hardening.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc",
        "value": "Start",
        "value_type": "dword",
        "on": 4,
        "off": 3,
    },
    {
        "id": "safe_dll_search",
        "name": "Safe DLL Search Mode",
        "category": "security",
        "info": "CWDIllegalInDllSearch = 0xFFFFFFFF. Forces Windows to search system dirs before cwd for DLLs — stops DLL hijacking.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Session Manager",
        "value": "CWDIllegalInDllSearch",
        "value_type": "dword",
        "on": 4294967295,
        "off": 0,
    },
    {
        "id": "clear_pagefile_shutdown",
        "name": "Clear Pagefile at Shutdown",
        "category": "security",
        "info": "Overwrites pagefile on shutdown so memory artifacts aren't left on disk. Slows shutdown noticeably.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management",
        "value": "ClearPageFileAtShutdown",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_subsystems",
        "name": "Disable POSIX/OSX Subsystems",
        "category": "security",
        "info": "Removes optional legacy subsystems from the Windows loader. Shrinks kernel attack surface.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Session Manager\SubSystems",
        "value": "Optional",
        "value_type": "sz",
        "on": "",
        "off": "POSIX",
    },
    {
        "id": "filter_administrator_token",
        "name": "Filter Built-in Admin Token",
        "category": "security",
        "info": "Built-in Administrator runs with split token like normal admins. UAC prompts apply even to Administrator account.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "FilterAdministratorToken",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "consent_prompt_behavior_admin",
        "name": "Always Prompt Admin Consent",
        "category": "security",
        "info": "ConsentPromptBehaviorAdmin = 2. Admins must confirm UAC on secure desktop — no auto-elevate for admins.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "ConsentPromptBehaviorAdmin",
        "value_type": "dword",
        "on": 2,
        "off": 5,
    },
    {
        "id": "disable_cached_logons",
        "name": "Disable Cached Logons",
        "category": "security",
        "info": "CachedLogonsCount = 0. Domain passwords won't be cached locally — can't log in offline, but safer if laptop stolen.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon",
        "value": "CachedLogonsCount",
        "value_type": "dword",
        "on": 0,
        "off": 10,
    },
    {
        "id": "disable_guest_account",
        "name": "Disable Guest Account",
        "category": "security",
        "info": "Sets the Guest account to disabled via SAM policy. Closes anonymous local access paths.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "value": "EnableGuestAccount",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_print_spooler",
        "name": "Disable Print Spooler",
        "category": "security",
        "info": "Disables Spooler service start. Mitigates PrintNightmare-style remote print driver attacks. No printing when off.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Services\Spooler",
        "value": "Start",
        "value_type": "dword",
        "on": 4,
        "off": 2,
    },
    {
        "id": "disable_ts_sessions",
        "name": "Disable Multiple RDP Sessions",
        "category": "security",
        "info": "fSingleSessionPerUser = 1. Only one session per user for remote desktop — limits concurrent RDP abuse.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server",
        "value": "fSingleSessionPerUser",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_network_selection_ui",
        "name": "Hide Network Selection UI",
        "category": "security",
        "info": "Hides network selection on logon screen. Stops someone from seeing/joining nearby Wi-Fi before login.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\System",
        "value": "DontDisplayNetworkSelectionUI",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_windows_store_auto_download",
        "name": "Disable Store Auto-Download",
        "category": "privacy",
        "info": "Stops the Microsoft Store from silently downloading and installing promoted apps.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsStore",
        "value": "AutoDownload",
        "value_type": "dword",
        "on": 2,
        "off": 4,
    },
    {
        "id": "disable_store_suggestions",
        "name": "Disable Store Suggestions",
        "category": "privacy",
        "info": "Turns off app suggestions inside the Microsoft Store.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\WindowsStore",
        "value": "DisableStoreApps",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_diagnostic_data_viewer",
        "name": "Disable Diagnostic Data Viewer",
        "category": "privacy",
        "info": "Blocks the Diagnostic Data Viewer from collecting extra telemetry beyond base Windows settings.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "value": "DisableOneSettingsDownloads",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_ceip",
        "name": "Disable CEIP Participation",
        "category": "privacy",
        "info": "Opts out of Customer Experience Improvement Program data collection across Windows components.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\SQMClient\Windows",
        "value": "CEIPEnable",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_app_diagnostics",
        "name": "Disable App Diagnostics Access",
        "category": "privacy",
        "info": "Default deny for app diagnostics — apps can't read info about other running apps.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_contacts_access",
        "name": "Block Contacts Access",
        "category": "privacy",
        "info": "Default deny for contacts. Apps can't read your contact list unless you allow per-app.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_calendar_access",
        "name": "Block Calendar Access",
        "category": "privacy",
        "info": "Default deny for calendar data. Stops apps from reading your schedule without permission.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appointments",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_notifications_access",
        "name": "Block Notification Access",
        "category": "privacy",
        "info": "Default deny for notification listener access. Stops apps from reading your notifications.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_account_info_access",
        "name": "Block Account Info Access",
        "category": "privacy",
        "info": "Default deny for reading account info (name, picture, etc.) from other apps.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userAccountInformation",
        "value": "Value",
        "value_type": "sz",
        "on": "Deny",
        "off": "Allow",
    },
    {
        "id": "disable_recent_docs",
        "name": "Disable Recent Documents",
        "category": "explorer",
        "info": "Stops Windows from tracking recently opened files in Jump Lists and Start. Good for shared machines.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "value": "NoRecentDocsHistory",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_jump_lists",
        "name": "Disable Jump Lists",
        "category": "explorer",
        "info": "Turns off taskbar Jump Lists so recent items aren't shown when you right-click icons.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "value": "NoStartMenuMFUprogramsList",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_thumbnail_cache",
        "name": "Disable Thumbnail Cache",
        "category": "explorer",
        "info": "Stops Explorer from saving thumbnail databases. Reduces forensic artifacts from viewed images.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\Explorer",
        "value": "DisableThumbsDBOnNetworkFolders",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_recent_shares",
        "name": "Disable Recent Share List",
        "category": "explorer",
        "info": "Hides recently used network share paths in Explorer address bar history.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "value": "NoRecentDocsNetHistory",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_toast_notifications",
        "name": "Disable Toast Notifications",
        "category": "explorer",
        "info": "Turns off app toast notifications system-wide for your user account.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications",
        "value": "ToastEnabled",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
    {
        "id": "disable_explorer_auto_suggest",
        "name": "Disable Explorer Auto-Suggest",
        "category": "explorer",
        "info": "Stops Explorer from sending keystrokes to Microsoft for autocomplete suggestions in the address bar.",
        "hive": "HKCU",
        "path": r"SOFTWARE\Policies\Microsoft\Windows\Explorer",
        "value": "DisableSearchBoxSuggestions",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_superfetch",
        "name": "Disable Superfetch (SysMain Policy)",
        "category": "explorer",
        "info": "Policy flag to disable SysMain/Superfetch prefetching. Can reduce disk activity and background I/O.",
        "hive": "HKLM",
        "path": r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters",
        "value": "EnablePrefetcher",
        "value_type": "dword",
        "on": 0,
        "off": 3,
    },
    {
        "id": "disable_office_telemetry",
        "name": "Disable Office Telemetry Policy",
        "category": "privacy",
        "info": "Policy to limit Office telemetry if Office is installed. Reduces data sent from Word/Excel/etc.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Office\16.0\Common\Privacy",
        "value": "PrivacyEnabled",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_edge_first_run",
        "name": "Disable Edge First Run Experience",
        "category": "privacy",
        "info": "Skips Edge first-run wizard and default browser nag screens on new profiles.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Edge",
        "value": "HideFirstRunExperience",
        "value_type": "dword",
        "on": 1,
        "off": 0,
    },
    {
        "id": "disable_edge_signin",
        "name": "Disable Edge Sign-In Sync",
        "category": "privacy",
        "info": "Blocks forced Edge sign-in and sync prompts. Keeps browsing data local unless you opt in.",
        "hive": "HKLM",
        "path": r"SOFTWARE\Policies\Microsoft\Edge",
        "value": "BrowserSignin",
        "value_type": "dword",
        "on": 0,
        "off": 1,
    },
]
