"""Windows services to disable for OPSEC / hardening.

Toggle ON = service disabled (hardened).
"""

SERVICE_TWEAKS = [
    {
        "id": "diagtrack",
        "name": "DiagTrack",
        "info": "Connected User Experiences and Telemetry. Sends detailed usage data to Microsoft. Top priority to kill.",
        "service": "DiagTrack",
        "default_start": "auto",
    },
    {
        "id": "dmwappushservice",
        "name": "dmwappushservice",
        "info": "WAP Push Message Routing — routes push messages for carrier/OEM bloat. Not needed on desktops.",
        "service": "dmwappushservice",
        "default_start": "auto",
    },
    {
        "id": "remote_registry",
        "name": "Remote Registry",
        "info": "Allows remote users to edit the registry over the network. Disable unless you do remote admin.",
        "service": "RemoteRegistry",
        "default_start": "demand",
    },
    {
        "id": "wersvc",
        "name": "Windows Error Reporting",
        "info": "Collects and sends crash dumps to Microsoft. Disable for privacy and to reduce outbound data.",
        "service": "WerSvc",
        "default_start": "manual",
    },
    {
        "id": "mapsbroker",
        "name": "Downloaded Maps Manager",
        "info": "Manages offline map data for the Maps app. Background downloads and location-related traffic.",
        "service": "MapsBroker",
        "default_start": "auto",
    },
    {
        "id": "lfsvc",
        "name": "Geolocation Service",
        "info": "Monitors your physical location for apps. Disable if you don't use location features.",
        "service": "lfsvc",
        "default_start": "demand",
    },
    {
        "id": "sharedaccess",
        "name": "Internet Connection Sharing",
        "info": "ICS — shares your internet connection with other devices. Attack surface if you don't use hotspot sharing.",
        "service": "SharedAccess",
        "default_start": "manual",
    },
    {
        "id": "phonesvc",
        "name": "Phone Service",
        "info": "Manages phone call state between PC and phone. Not needed unless you use Phone Link heavily.",
        "service": "PhoneSvc",
        "default_start": "manual",
    },
    {
        "id": "wisvc",
        "name": "Windows Insider Service",
        "info": "Handles Windows Insider preview builds and feedback. Disable on stable/production machines.",
        "service": "wisvc",
        "default_start": "manual",
    },
    {
        "id": "xblauthmanager",
        "name": "Xbox Live Auth Manager",
        "info": "Provides Xbox Live auth for games and Game Bar. Safe to disable if you don't use Xbox features.",
        "service": "XblAuthManager",
        "default_start": "manual",
    },
    {
        "id": "xblgamesave",
        "name": "Xbox Live Game Save",
        "info": "Syncs Xbox game saves to the cloud. Disable if you don't use Xbox on this PC.",
        "service": "XblGameSave",
        "default_start": "manual",
    },
    {
        "id": "xboxgipsvc",
        "name": "Xbox Accessory Management",
        "info": "Manages Xbox controllers and accessories. Not needed without Xbox hardware.",
        "service": "XboxGipSvc",
        "default_start": "manual",
    },
    {
        "id": "xboxnetapisvc",
        "name": "Xbox Live Networking",
        "info": "Xbox Live networking stack. Disable if you don't play Xbox games on this machine.",
        "service": "XboxNetApiSvc",
        "default_start": "manual",
    },
    {
        "id": "wmpnetworksvc",
        "name": "Windows Media Player Sharing",
        "info": "Shares Windows Media Player library over the network. Unnecessary exposure on most PCs.",
        "service": "WMPNetworkSvc",
        "default_start": "manual",
    },
    {
        "id": "trkwks",
        "name": "Distributed Link Tracking",
        "info": "Maintains links across NTFS volumes in a domain. Rarely needed on standalone/home PCs.",
        "service": "TrkWks",
        "default_start": "auto",
    },
    {
        "id": "remoteaccess",
        "name": "Routing and Remote Access",
        "info": "Legacy VPN/routing service. Disable unless you run Windows as a router or legacy VPN server.",
        "service": "RemoteAccess",
        "default_start": "demand",
    },
    {
        "id": "fax",
        "name": "Fax Service",
        "info": "Windows Fax. Almost nobody uses this — safe to disable on any modern PC.",
        "service": "Fax",
        "default_start": "manual",
    },
    {
        "id": "cdpsvc",
        "name": "Connected Devices Platform",
        "info": "Syncs activities across devices (Your Phone, cross-device features). Disable for privacy.",
        "service": "CDPSvc",
        "default_start": "auto",
    },
    {
        "id": "wdiservicehost",
        "name": "Diagnostic Service Host",
        "info": "Hosts diagnostic modules for Windows troubleshooting. Sends diagnostic data when problems occur.",
        "service": "WdiServiceHost",
        "default_start": "manual",
    },
    {
        "id": "wdisystemhost",
        "name": "Diagnostic System Host",
        "info": "System-level diagnostic host. Part of Windows telemetry and troubleshooting pipeline.",
        "service": "WdiSystemHost",
        "default_start": "manual",
    },
    {
        "id": "diagnosticshub",
        "name": "Diagnostic Hub Collector",
        "info": "Collects real-time diagnostic events for Visual Studio / Windows diagnostics. Privacy concern.",
        "service": "diagnosticshub.standardcollector.service",
        "default_start": "manual",
    },
    {
        "id": "dosvc",
        "name": "Delivery Optimization",
        "info": "P2P Windows Update sharing with other machines. Disable to stop your PC sharing updates on the network.",
        "service": "DoSvc",
        "default_start": "auto",
    },
    {
        "id": "ssdpsrv",
        "name": "SSDP Discovery",
        "info": "Discovers UPnP devices on the network. Used in local network discovery attacks — disable if not needed.",
        "service": "SSDPSRV",
        "default_start": "manual",
    },
    {
        "id": "upnphost",
        "name": "UPnP Device Host",
        "info": "Hosts UPnP devices. Part of the UPnP stack that can be abused for network pivoting.",
        "service": "upnphost",
        "default_start": "manual",
    },
    {
        "id": "winhttp_autoproxy",
        "name": "WinHTTP Web Proxy Auto-Discovery",
        "info": "Discovers proxy settings via WPAD. Disable to close MITM/proxy injection on local networks.",
        "service": "WinHttpAutoProxySvc",
        "default_start": "manual",
    },
    {
        "id": "pnrpsvc",
        "name": "Peer Name Resolution Protocol",
        "info": "PNRP — peer-to-peer name resolution. Rarely needed and expands network attack surface.",
        "service": "PNRPsvc",
        "default_start": "manual",
    },
    {
        "id": "termservice",
        "name": "Remote Desktop Services",
        "info": "Core RDP service. Disable if you never remote into this PC. Same effect as disabling RDP in registry.",
        "service": "TermService",
        "default_start": "manual",
    },
    {
        "id": "retaildemo",
        "name": "Retail Demo Service",
        "info": "Retail demo mode for store PCs. Should never run on a personal machine.",
        "service": "RetailDemo",
        "default_start": "manual",
    },
    {
        "id": "edgeupdate",
        "name": "Microsoft Edge Update",
        "info": "Background Edge updater. Disable if you manage Edge updates yourself or don't use Edge.",
        "service": "edgeupdate",
        "default_start": "auto",
    },
    {
        "id": "edgeupdatem",
        "name": "Microsoft Edge Update (Manual)",
        "info": "Manual Edge update service companion. Disable alongside edgeupdate for full control.",
        "service": "edgeupdatem",
        "default_start": "manual",
    },
    {
        "id": "icssvc",
        "name": "Windows Mobile Hotspot",
        "info": "Provides mobile hotspot sharing. Disable if you don't share your connection as a hotspot.",
        "service": "icssvc",
        "default_start": "manual",
    },
    {
        "id": "frameserver",
        "name": "Camera Frame Server",
        "info": "Shares camera frames between apps. Disable if you want to reduce camera access paths.",
        "service": "FrameServer",
        "default_start": "manual",
    },
    {
        "id": "tzautoupdate",
        "name": "Auto Time Zone Updater",
        "info": "Automatically sets timezone from location. Sends location-ish signals — disable for privacy.",
        "service": "tzautoupdate",
        "default_start": "manual",
    },
]

SERVICE_BY_ID = {s["id"]: s for s in SERVICE_TWEAKS}
